export const surpriseMePrompts = [
        'Avocado Nebula Seat',
        'Galactic Feline Checkers: A Dalí Odyssey',
        'Ukiyo-e Teddy Bear Space Grocers',
        'Cosmic Chess with Matisses Mech',
        'Panda Stellar Alchemist: Sparkle Elixir',
        'Tiny Surf Planets: Rodent Wave Riders',
        'Interstellar Aquarium: Neon Tetra Nebula',
        'Exoplanet Resort: Astronaut R&R',
        'Regal Capybara in the Milky Way',
        'Cosmic Diner: Stained Glass Fast-Food',
        'Future Urban Lightscape: Sky-car Dreams',
        'Intergalactic Lounge: Dual Nebula Pools',
        'Burger Divination: Shiba Inu Astrologer',
        'Galactic Otter with Cosmic Pearl Earring',
        'Starry Night Fox in Galactic Flight',
        'Alien Soup Monster: Knitted Nebula',
        'Yellow-Space Companion: Plush Toy Mech',
        'Synthwave Sunset: Ocean of Stars',
        'Bio-Dome Skybridge: Future Towers',
        'Rainbow Nebula Voyage: Hot Air Balloon',
        'Sonar Superhero: Comic Cover Cosmos',
        'Big Bang: Colorful Nebula Genesis',
        'Interspecies Love: Samoyed and Siamese in Space',
        'Cosmic Creature: Purple Room Encounter',
        'DJ David: Marble Beats in Space',
        'Mars Samurai: Red Planet Warrior',
        'Cadillac Space Cruise: Toronto Nebula',
        'Blue-eyed Star Maiden: Human Odyssey',
        'Interdimensional Stargate Wanderer',
        'Spongebob in the Witch Star Cluster',
        'Velociraptor Hotdog Vendor: Jurassic Space',
        'Neon Kowloon: Starlight Street Walker',
        'Living BBQ: Pixar Star Griller',
        'Neon Cyborg Nightclub: Dance of the Androids',
        'Star Wars: Lost Anime of the Galaxy',
        'Rubik’s Cube Burger: Puzzle Bites in Space',
        'Blade Runner Hedgehog: Synthwave Spines',
        'Extraterrestrial Encounter: Alien Planet Odyssey',
        'Dinosaur Cape Town Explorer: Jurassic Journey',
        'Silicon Romance: Man and Machine',
        'Cyborg Tokyo Night Walk: Neon Circuit',
        'Vampire NYC Noir: Dracula in the Roaring Twenties',
        'Synthwave Sky Explorer: Neon Airplane',
        'Neon Drizzle: Tokyo Rain Wanderer',
        'Space Shuttle Cape Town: Earth Orbit Journey',
];
//todo dodać pozostałe fazy księżyca, ikonki od nich
export const weatherData = {
  moon: ['new moon', 'waxing crescent', 'first quarter', ''],
  clody: ['slightly cloudy', 'partly cloudy', 'mostly cloudy', 'very cloudy'],
  fog: ['slightly foggy', 'moderately foggy', 'very foggy']
};